AWSTemplateFormatVersion: 2010-09-09

Parameters:
  CodeBuildRole:
    Type: String

Resources:

  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub "${AWS::StackName}-StaticWebsiteBuild"
      ServiceRole: !Ref CodeBuildRole
      Source:
        Type: CODEPIPELINE
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:6.0
        Type: LINUX_CONTAINER

Outputs:
  CodeBuildProjectName:
    Value: !Ref CodeBuildProject
