AWSTemplateFormatVersion: 2010-09-09

Parameters:
  DomainName:
    Type: String
  HostedZoneId:
    Type: String
  CloudFrontDomainName:
    Type: String

Resources:
  WebsiteDNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        DNSName: !Ref CloudFrontDomainName
        HostedZoneId: !Ref Z2FDTNDATAQYW2

Outputs:
  DNSRecordName:
    Value: !Ref DomainName
